name: Build Signed Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Release APK
      run: ./gradlew assembleRelease --no-daemon --stacktrace
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon --stacktrace
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: OfflineDayPlanner-Release-APK
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 90
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: OfflineDayPlanner-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 90
        
    - name: Get APK Info
      run: |
        echo "=== Release APK Info ==="
        ls -la app/build/outputs/apk/release/
        echo "=== Debug APK Info ==="
        ls -la app/build/outputs/apk/debug/
