name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: List project structure
      run: |
        echo "=== Project structure ==="
        find . -type f -name "*.kt" -o -name "*.xml" -o -name "*.gradle*" | head -20
        
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Check APK output
      run: |
        echo "=== APK files ==="
        find . -name "*.apk" -type f
        echo "=== Build outputs ==="
        ls -la app/build/outputs/apk/debug/ || echo "No debug APK directory"
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: OfflineDayPlanner-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
